#### Intern Buddy Data Science Candidate Shortlisting.

InternBuddy is a platform where people who have prepared themselves for Data Science jobs and are looking for an entry into this industry. Job seekers could post their profile on the web portal of InternBuddy and, based on the scoring criteria of the system they are shortlisted and forwarded to the recruiters.
This helps the recruiters to only go through a limited number of profiles instead of reading each and every file submitted.

Here I have prepared a model which helps the system understand the profiles that are to be considered for shortlisting and the rest to be ignored.

Lets start by importing the required Libraries and the dataset for analysis.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings
import datetime as dt

pd.set_option('display.max_column',10000) 
pd.set_option('display.max_colwidth',10000)  
pd.set_option('display.max_rows',10000)

Importing the dataset using the pandas library.
As we have a excel file lets use pandas.read_excel command for dataset import

In [2]:
ibdf=pd.read_excel('Data_Science_2020_v2.xlsx')

Lets have a look at the dataframe and get an idea about the file.

In [3]:
ibdf.head()

,Application_ID,Current City,Python (out of 3),R Programming (out of 3),Data Science (out of 3),Other skills,Institute,Degree,Stream,Current Year Of Graduation,Performance_PG,Performance_UG,Performance_12,Performance_10
0,DS0001,Bangalore,1,0,3,"Machine Learning, Arduino, C Programming, CSS, Data Analytics, Data Structures, Deep Learning, HTML, Natural Language Processing (NLP), MATLAB, Python",Global Academy of Technology,Bachelor of Engineering (B.E),Electrical and Electronics Engineering,2019,NaN,7.73/10,NaN,NaN
1,DS0002,Mumbai,2,1,2,"AutoCAD, MS-Office, Machine Learning, Microsoft Azure, MySQL, Python, SolidWorks, Deep Learning, R Programming","Aegis School Of Business, Data Science, Cyber Security And Telecommunication",NaN,PGP,2020,NaN,68.00/100,NaN,NaN
2,DS0003,Mumbai,2,0,0,"C++ Programming, Data Structures, Image Processing, Python","VJTI, Mumbai",Bachelor of Technology (B.Tech),Information Systems,2018,NaN,8.85/10,91.40/91.40,9.40/9.40
3,DS0004,Dhanbad,2,0,2,"Algorithms, C++ Programming, Data Structures, Natural Language Processing (NLP), CSS, Computer Vision, Deep Learning, HTML, Java, Machine Learning, MySQL, Python, Android",IIT (ISM) Dhanbad,Integrated M.Tech,Mathematics and Computing,2021,NaN,8.40/10,91.80/91.80,10.00/10.00
4,DS0005,Bangalore,2,0,0,"MS-Word, Python, SQL, MS-Excel",Vvce,Bachelor of Engineering (B.E),Electronics and Communication,2018,NaN,NaN,NaN,NaN

As you can see there are many records and to read each row and find out the quality of data will be difficult for us. 
So lets perform some data quality checks and see what needs to be done on the data to proceed with analysis.

In [4]:
# This command will show the number of rows and the columns in the dataframe
ibdf.shape

(611, 14)

In [5]:
# We can list down all the column names that are there in the dataframe
ibdf.columns

Index(['Application_ID', 'Current City', 'Python (out of 3)',
       'R Programming (out of 3)', 'Data Science (out of 3)', 'Other skills',
       'Institute', 'Degree', 'Stream', 'Current Year Of Graduation',
       'Performance_PG', 'Performance_UG', 'Performance_12', 'Performance_10'],
      dtype='object')

#### - Info() command will give us a basic idea like:
    1. What are the number of rows
    2. How many columns are there?
    3. What are the Datatypes of different columns?
    4. Are there any null values?
    5. How much memory is being consumed by the dataframe?
#### So lets check the info() command

In [6]:
ibdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 611 entries, 0 to 610
Data columns (total 14 columns):
Application_ID                611 non-null object
Current City                  611 non-null object
Python (out of 3)             611 non-null int64
R Programming (out of 3)      611 non-null int64
Data Science (out of 3)       611 non-null int64
Other skills                  601 non-null object
Institute                     611 non-null object
Degree                        575 non-null object
Stream                        580 non-null object
Current Year Of Graduation    611 non-null int64
Performance_PG                128 non-null object
Performance_UG                533 non-null object
Performance_12                363 non-null object
Performance_10                339 non-null object
dtypes: int64(4), object(10)
memory usage: 67.0+ KB

#### This will help us in having a descriptive statistics about the dataset like minimum, maximum, counts, sum, unique, standard deviation, quartile values etc.

In [7]:
ibdf.describe(include='all')

,Application_ID,Current City,Python (out of 3),R Programming (out of 3),Data Science (out of 3),Other skills,Institute,Degree,Stream,Current Year Of Graduation,Performance_PG,Performance_UG,Performance_12,Performance_10
count,611,611,611.000000,611.000000,611.000000,601,611,575,580,611.000000,128,533,363,339
unique,611,70,NaN,NaN,NaN,513,439,42,120,NaN,83,269,204,155
top,DS0264,Bangalore,NaN,NaN,NaN,"Data Analytics, Machine Learning, Python",Great Lakes Institute of Management,Bachelor of Technology (B.Tech),Computer Science,NaN,8.00/10,70.00/100,86.00/86.00,10.00/10.00
freq,1,334,NaN,NaN,NaN,5,21,168,72,NaN,6,15,8,24
mean,NaN,NaN,1.788871,0.582651,0.872340,NaN,NaN,NaN,NaN,2018.487725,NaN,NaN,NaN,NaN
std,NaN,NaN,0.780673,0.918459,1.014681,NaN,NaN,NaN,NaN,2.573082,NaN,NaN,NaN,NaN
min,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,2004.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,2018.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,2.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,2.000000,1.000000,2.000000,NaN,NaN,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,3.000000,3.000000,3.000000,NaN,NaN,NaN,NaN,2023.000000,NaN,NaN,NaN,NaN

In [8]:
# Checking the datatypes of the dataframe
ibdf.dtypes

Application_ID                object
Current City                  object
Python (out of 3)              int64
R Programming (out of 3)       int64
Data Science (out of 3)        int64
Other skills                  object
Institute                     object
Degree                        object
Stream                        object
Current Year Of Graduation     int64
Performance_PG                object
Performance_UG                object
Performance_12                object
Performance_10                object
dtype: object

- To perform analysis we need to make sure there are no missing values in our data. So lets check the missing values in the dataframe and find its percentage.

In [9]:
(ibdf.isnull().sum()*100)/ibdf.shape[0]

Application_ID                 0.000000
Current City                   0.000000
Python (out of 3)              0.000000
R Programming (out of 3)       0.000000
Data Science (out of 3)        0.000000
Other skills                   1.636661
Institute                      0.000000
Degree                         5.891980
Stream                         5.073650
Current Year Of Graduation     0.000000
Performance_PG                79.050736
Performance_UG                12.765957
Performance_12                40.589198
Performance_10                44.517185
dtype: float64

In [10]:
ibdf.loc[(ibdf['Performance_PG']=='NA') & (ibdf['Performance_UG']=='NA') & (ibdf['Current Year Of Graduation']<=2020)].index
ibdf.drop(index=ibdf.loc[(ibdf['Performance_PG']=='NA') & (ibdf['Performance_UG']=='NA') & (ibdf['Current Year Of Graduation']<=2020)].index,inplace=True)

- As per the analysis carried out till now we can make out that the columns Application_ID, Performance_10, Performance_12, Performance_PG, and Performance_UG are not required for shortlisting the candidates as these details are not required in the shortlisting criteria document. 
- Lets proceed with dropping these features and see the shape of the dataframe

In [11]:
Application_ID=ibdf.pop('Application_ID')
ibdf.pop('Performance_10')
ibdf.pop('Performance_12')
ibdf.pop('Performance_PG')
ibdf.pop('Performance_UG')
print(ibdf.shape)
ibdf.head()

(611, 9)

,Current City,Python (out of 3),R Programming (out of 3),Data Science (out of 3),Other skills,Institute,Degree,Stream,Current Year Of Graduation
0,Bangalore,1,0,3,"Machine Learning, Arduino, C Programming, CSS, Data Analytics, Data Structures, Deep Learning, HTML, Natural Language Processing (NLP), MATLAB, Python",Global Academy of Technology,Bachelor of Engineering (B.E),Electrical and Electronics Engineering,2019
1,Mumbai,2,1,2,"AutoCAD, MS-Office, Machine Learning, Microsoft Azure, MySQL, Python, SolidWorks, Deep Learning, R Programming","Aegis School Of Business, Data Science, Cyber Security And Telecommunication",NaN,PGP,2020
2,Mumbai,2,0,0,"C++ Programming, Data Structures, Image Processing, Python","VJTI, Mumbai",Bachelor of Technology (B.Tech),Information Systems,2018
3,Dhanbad,2,0,2,"Algorithms, C++ Programming, Data Structures, Natural Language Processing (NLP), CSS, Computer Vision, Deep Learning, HTML, Java, Machine Learning, MySQL, Python, Android",IIT (ISM) Dhanbad,Integrated M.Tech,Mathematics and Computing,2021
4,Bangalore,2,0,0,"MS-Word, Python, SQL, MS-Excel",Vvce,Bachelor of Engineering (B.E),Electronics and Communication,2018

- As it is clearly mentioned in the shortlisting criteria that only candidates who are having graduation year 2020 and less than that are considered for shortlisting 
We will have to drop the records which are having graduation year greater than 2020

In [12]:
# Dropping records having graduation year greater than 2020
ibdf.drop(ibdf.loc[(ibdf['Current Year Of Graduation']>2020)].index)

,Current City,Python (out of 3),R Programming (out of 3),Data Science (out of 3),Other skills,Institute,Degree,Stream,Current Year Of Graduation
0,Bangalore,1,0,3,"Machine Learning, Arduino, C Programming, CSS, Data Analytics, Data Structures, Deep Learning, HTML, Natural Language Processing (NLP), MATLAB, Python",Global Academy of Technology,Bachelor of Engineering (B.E),Electrical and Electronics Engineering,2019
1,Mumbai,2,1,2,"AutoCAD, MS-Office, Machine Learning, Microsoft Azure, MySQL, Python, SolidWorks, Deep Learning, R Programming","Aegis School Of Business, Data Science, Cyber Security And Telecommunication",NaN,PGP,2020
2,Mumbai,2,0,0,"C++ Programming, Data Structures, Image Processing, Python","VJTI, Mumbai",Bachelor of Technology (B.Tech),Information Systems,2018
4,Bangalore,2,0,0,"MS-Word, Python, SQL, MS-Excel",Vvce,Bachelor of Engineering (B.E),Electronics and Communication,2018
7,Bangalore,2,2,0,"Natural Language Processing (NLP), Python, R Programming, SQL","Government Engineering College, Bhuj",B.Tech (Hons.),Mining,2016
9,Bangalore,0,0,0,"CSS, HTML, JavaScript, PostgreSQL","MS Ramaiah College Of Arts, Science And Commerce, BANGALORE",Master of Business Administration_(MBA),Marketing,2019
11,Bangalore,1,2,2,"MS-Excel, MS-Office, SPSS, Data Science, Machine Learning, R Programming, SQL, Python","Devi Ahilya Vishwavidyalaya,Indore",Master of Science (M.Sc),Statistics,2019
12,Bangalore,0,0,0,"C Programming, Eclipse (IDE), Java, Database Management System (DBMS), HTML, Linux, SQL",The Oxford College of Engineering,Bachelor of Engineering (B.E),Computer Science & Engineering,2018
13,Bangalore,0,0,0,"AutoCAD, MS-Office, Catia, SolidWorks","SJB Institute of Technology, Bangalore",Bachelor of Engineering (B.E),Mechanical Engineering,2018
14,Chennai,3,0,3,"Machine Learning, Python, MySQL, Statistical Modeling, Tableau",Great Lakes Institute of Management,Post Graduate Programme (PGP),Data Science Engineering,2020
15,Hyderabad,0,0,0,"AutoCAD, Embedded Systems, MATLAB",VVIT,Bachelor of Technology (B.Tech),Information Systems,2019
16,Bangalore,2,0,1,"Bootstrap, C Programming, Flask, HTML, LARAVEL, MySQL, Node.js, PHP, PostgreSQL, Python, SQL, Stripe Payment API, Video Editing, Data Analytics, GitHub, Heroku, Image Processing, Machine Learning",Acharya Institute of Management and Sciences,Master of Computer Applications (MCA),Computer Application,2020
17,Bangalore,0,0,0,"Data Analytics, MS-Excel",Balaji Institute Of Pharmaceutical Sciences,Bachelor of Pharmacy (B.Pharm),NaN,2014
18,Nellore,2,0,2,"C Programming, Data Analytics, Data Science, Java, Machine Learning, Natural Language Processing (NLP), Python, SQL, Unix, HTML",Krishna Chaitanya Institute Of Science And Technology,Integrated MCA,NaN,2020
19,Thrissur,1,0,0,"HTML, MS-Excel, SQL, Android, JavaScript, PHP, Python",Sree Narayana Guru Institute Of Science And Management,Master of Computer Applications (MCA),Computer Application,2017
20,Pathanamthitta,1,1,1,"Data Analytics, Embedded Systems, Machine Learning, Python, R Programming",Mangalam College Of Engineering,B.Tech (Hons.),Electronics and Communication,2019
21,Bangalore,2,0,0,"Algorithms, C Programming, Data Structures, Database Management System (DBMS), Java, Linux, Python",Jain University,B.Tech (Hons.),Computer Science And Engineering,2020
22,Bangalore,3,0,0,"Python, SQL, Amazon Web Services (AWS), Apache Cassandra, Apache Kafka, BIG DATA ANALYTICS, Cloud Computing, Database Management System (DBMS), Hadoop, Linux, MongoDB, Shell Scripting",V.V.P. Engineering College,Bachelor of Engineering (B.E),Computer Science,2019
23,Bangalore,3,1,2,"Python, Machine Learning, SQL, R Programming",Don Bosco Institute of Technology,Bachelor of Engineering (B.E),Electronics and Communication,2019
24,Bangalore,3,0,2,"Python, Data Analytics, Data Science, MS-PowerPoint, MS-Word, Machine Learning, Mathematics, Video Editing, C Programming, Data Structures, Database Management System (DBMS), MS SQL Server, MySQL, SQL",Sri Sairam College Of Engineering,Bachelor of Engineering (B.E),Computer Science,2020
25,Visakhapatnam,0,0,0,NaN,Andhra University,Bachelor of Technology (B.Tech),Instrumentation and Control Engineering,2018
26,Bangalore,2,0,2,"Computer Networking, Data Analytics, Data Science, Linux, MS-Excel, Machine Learning, Python, SQL","M.S. Ramaiah Institute of Technology , Bangalore",Bachelor of Engineering (B.E),Electronics and Communication,2017
30,Delhi,2,0,2,"Data Analytics, Java, Machine Learning, Python, SQL","Amity University, Noida",Bachelor of Technology (B.Tech),Information Systems,2019
31,Hyderabad,2,2,2,"Machine Learning, Python, R Programming, Natural Language Processing (NLP)",mvgr college of engineering,Bachelor of Technology (B.Tech),Mechanical Engineering,2019
32,Bangalore,1,0,0,"English Proficiency (Spoken), MS-Excel, Data Analytics, Python",Sacred Heart College (Autonomous),Bachelor of Commerce (B.Com),Commerce,2016
33,Bangalore,1,0,0,"English Proficiency (Spoken), C Programming, C++ Programming, English Proficiency (Written), HTML, Hindi Proficiency (Spoken), Java, MS-Excel, MS-Office, Malayalam, MySQL, Python","CMR Institute of Technology, Bangalore",Bachelor of Technology (B.Tech),NaN,2020
34,Mumbai,2,2,2,"Machine Learning, Python, R Programming, Artifical Intelligence, Data Analytics, Deep Learning, Natural Language Processing (NLP)","National Institute Of Electronics & Information Technology, Calicut",NaN,Artificial Intelligence,2020
35,Kolkata,2,0,3,"ASP.NET, C#, HTML, JavaScript, Machine Learning, SQL, Data Science, Python, Statistical Modeling",BIDHAN CHANDRA KRISHI VISWAVIDYALAYA,B.Tech (Hons.),Agriculture & Food Engineering,2009
36,Bhiwadi,0,0,0,"PLC SCADA, Embedded Systems, MATLAB, MS-Office, VHDL, C Programming, MS-Excel",IIT ISM Dhanbad,Master of Technology (M.Tech),Electronics and Telecommunication Engineering (ETE),2020
39,Bangalore,2,2,2,"Machine Learning, Python, R Programming, Statistical Modeling, Apache, Hadoop",Visvesvaraya Technological University,Master of Technology (M.Tech),Engineering Design,2016
40,Bangalore,2,2,2,"C Programming, C++ Programming, Data Analytics, Java, MS-Excel, Machine Learning, MySQL, Python, R Programming, Statistical Modeling",NBN Sinhgad School Of Engineering,Bachelor of Engineering (B.E),Computer Science,2019
41,Thrissur,2,0,1,"C Programming, Python, Machine Learning",St Joseph's College Bangalore,Master of Science (M.Sc),Physics,2018
42,Bangalore,2,2,2,"Data Analytics, Data Science, Deep Learning, Machine Learning, Python, R Programming, SQLite, Apache, MySQL, SQL",Pt. Shambhu Nath Shukla University,Master of Science (M.Sc),Physics,2018
45,New Delhi,3,3,0,"C Programming, Python, R Programming",NIT Rourkela,Integrated B.Sc. & M.Sc.,Inetgrated Msc Student Of Mathematics,2019
46,Bangalore,3,0,3,"CSS, Django, HTML, Machine Learning, MySQL, Python, Data Analytics, Deep Learning, MATLAB, Neural Networks, OpenCV",Laxmi Narain College Of Technology,Bachelor of Engineering (B.E),Computer Science & Engineering,2018
47,Bangalore,0,0,3,"Machine Learning, C Programming, Data Science, Java",Alpha College of Engineering,Bachelor of Engineering (B.E),Computer Science Engineering,2019
48,Noida,0,0,0,Data Analytics,"Jayoti Vidyapeeth Women's University, Jaipur",Bachelor of Technology (B.Tech),Computer Science,2014
49,Bangalore,2,0,1,"C Programming, Computer Vision, Database Management System (DBMS), Digital Marketing, Mathematics, Data Analytics, Data Structures, Java, Python, XML, AngularJS, Machine Learning, OpenCV",Sir C R Reddy PG College,Master of Computer Applications (MCA),Computer Science,2009
50,Banglore,2,0,2,"Machine Learning, MySQL, Python, SAS, Statistical Modeling",KKR AND KSR INSTITUTE OF TECHNOLOGY AND SCIENCES,Bachelor of Technology (B.Tech),Computer Science,2017
51,Bangalore,2,0,3,"Data Analytics, Machine Learning, English Proficiency (Spoken), Java, MS-Excel, Python, SQL",Anamalai University,Master of Science (M.Sc),Computer Science,2019
52,Bangalore,3,0,2,"Python, AutoCAD, C Programming, C++ Programming, Java, Machine Learning, MySQL",Bangalore Institute Of Technology,Bachelor of Engineering (B.E),Electronics and Instrumentation,2020
53,Bangalore,3,0,3,"Data Analytics, Machine Learning, Python, Statistical Modeling, Computer Vision, Image Processing, MS-Excel, Natural Language Processing (NLP), Deep Learning",Varadha Reddy College Of Engineering,Bachelor of Technology (B.Tech),Electronics and Communication,2016
54,Chennai,2,0,2,"BIG DATA ANALYTICS, Data Analytics, Database Management System (DBMS), Machine Learning, MySQL, Natural Language Processing (NLP), Python",IIIT-Bangalore,Post Graduate Diploma,Data Science,2019
57,Bangalore,2,1,0,"MS-Excel, Python, SAP, R Programming, SPSS, SQL",Christ University Bangalore,Master of Arts (M.A.),Applied Economics,2012
58,Bangalore,2,2,0,"Java, MS-Excel, MS-PowerPoint, Python, R Programming",International School Of Engineering (INSOFE),NaN,Data Science,2020
59,Banglore,1,0,1,"English Proficiency (Spoken), MS-Excel, Machine Learning, Python",JNTU,Master of Technology (M.Tech),Computer Science,2015
60,Banglore,2,0,2,"English Proficiency (Spoken), English Proficiency (Written), MS-Excel, Machine Learning, Python",Imarticus Learning,PG Diploma in Data Science,Analytics,2020
61,Bangalore,0,2,0,R Programming,St.Josephs College Of Arts And Science,Bachelor of Science (B.Sc),Mathematics,2017
63,Hyderabad,2,0,2,"Machine Learning, Python, Data Analytics",SRM University Chennai,Integrated B.Tech,Automobile,2016
64,Bangalore,2,0,0,"C Programming, C++ Programming, CSS, HTML, Java, Python, SQL",Rungta College Of Engineering And Technology,Bachelor of Engineering (B.E),Computer Science Engineering,2019
65,Gulbarga,0,0,0,Data Science,"PDA College Of Engineering, Gulbarga, Karnataka",Bachelor of Engineering (B.E),Mechanical Engineering,2017
66,Bangalore,2,0,2,"Data Analytics, Deep Learning, Eclipse (IDE), HTML, MS-Excel, Machine Learning, MySQL, Python",KIIT UNIVERSITY,Bachelor of Technology (B.Tech),Information Technology,2018
68,Pune,0,2,2,"Data Analytics, Embedded Systems, Machine Learning, R Programming, Visual Basic (VB)",Imarticus Learning Pvt Ltd,NaN,Data Analytics,2020
69,Mumbai,2,0,1,"C Programming, C++ Programming, GNU Octave, Java, MS-Excel, MS-PowerPoint, MS-Word, Python, Machine Learning",Manipal University Jaipur,Bachelor of Technology (B.Tech),Mechanical Engineering,2019
70,Hyderabad,2,0,3,"Machine Learning, MySQL, Python",Great Lakes Institute Of Technology,Post Graduate Programme (PGP),Data Science And Engineering,2020
71,Banglore,1,1,0,"MS-Excel, MySQL, Python, R Programming, SAS, Statistical Modeling, Tableau","National Institute Of Electronics & Information Technology, Calicut",Master of Computer Applications (MCA),Computer Application,2015
73,Pune,0,0,1,"Hibernate (Java), MySQL, C Programming, C++ Programming, CSS, HTML, Java, Spring MVC, Machine Learning",KLS Gogte Institute Of Technology Belgaum,Bachelor of Engineering (B.E),Computer Science & Engineering,2017
75,Bangalore,2,2,2,"C Programming, C++ Programming, Data Analytics, MS-Excel, Machine Learning, Python, R Programming, SQL",New Horizon College of Engineering,Master of Technology (M.Tech),Computer Science & Engineering,2019
76,Bangalore,3,2,3,"Data Science, Deep Learning, Machine Learning, Natural Language Processing (NLP), Python, Artifical Intelligence, R Programming",IES College of Technology,Bachelor of Engineering (B.E),Computer Science,2019
77,Bangalore,2,0,1,"ASP.NET, C#, HTML, Python, SQL, Visual Basic (VB), Machine Learning","Mar Athanasius College Of Arts & Science, Kothamangalam,Kerala",Bachelor of Science (B.Sc),Mathematics,2014
78,Bangalore,1,0,0,"Python, SAS, SQL","GLA University,Mathura",Bachelor of Technology (B.Tech),Information Systems,2018
79,Hyderabad,1,0,0,"CSS, HTML, JavaScript, Data Science, Hadoop, MySQL, Python",JNTU ANANTHAPUR,B.Tech (Hons.),Electrical and Electronics Engineering,2019
80,Bangalore,2,0,0,"Java, Python, JavaScript, MongoDB, SQL",Greater Noida Institute Of Technology,Bachelor of Technology (B.Tech),computer science,2019
81,Pune,2,0,2,"Data Science, Machine Learning, Python, Data Analytics, Natural Language Processing (NLP), SQL, Tableau",William Carey University,Bachelor of Science (B.Sc),NaN,2017
82,Bangalore,2,0,2,"Deep Learning, Machine Learning, Natural Language Processing (NLP), Python, Statistical Modeling, BIG DATA ANALYTICS, MS-Excel, MongoDB",Manipal University,NaN,Data Science,2020
83,Vadodara,2,2,2,"Data Analytics, MS-Office, Machine Learning, MySQL, Python, R Programming, MongoDB",The Maharaja Sayajirao University of Baroda,Master of Statistics (M.Stat),Science,2020
84,Bangalore,2,0,2,"Data Analytics, HTML, Machine Learning, MySQL, Python, Deep Learning, Natural Language Processing (NLP)",Bmsce,Bachelor of Engineering (B.E),NaN,2019
85,Bangalore,2,0,2,"Data Analytics, C Programming, HTML, MS-Excel, MS-Word, Machine Learning, MySQL, Python, SQL, Flask, Heroku, Statistical Modeling, WordPress",Karmaveer Dadasaheb Kannamwar College Of Engineering,Bachelor of Engineering (B.E),Computer Science,2019
88,Bangalore,0,0,0,NaN,C.Byregowda Institute Of Technology,Bachelor of Engineering (B.E),Computer Science & Engineering,2020
89,Pune,1,1,0,"MS-Excel, Python, R Programming, SAS","Modern College Of Arts, Science & Commerce",Master of Science (M.Sc),Statistics,2019
90,Bangalore,2,0,1,"French Proficiency (spoken), MS-Excel, MS-Word, Python, SQL, Statistical Modeling, Data Analytics, Machine Learning",IGNOU,NaN,Post Graduate Diploma In Statistics,2020
91,Bangalore,3,3,0,"Data Science, Python, R Programming, Natural Language Processing (NLP), Tableau",Kingston Engineering College,Bachelor of Engineering (B.E),Electronics and Communication,2019
92,Bangalore,2,0,0,"Algorithms, C Programming, Data Structures, Database Management System (DBMS), Deep Learning, Natural Language Processing (NLP), Python, Android, Computer Vision, OpenCV",Government Engineering College Palakkad,Bachelor of Technology (B.Tech),IT,2019
93,Bangalore,3,0,2,"Adobe Premiere Pro, Python, Data Analytics, Database Management System (DBMS), Django, Machine Learning",Pondicherry University,Master of Computer Applications (MCA),Computer Science,2020
95,Bangalore,2,0,3,"Data Analytics, English Proficiency (Spoken), MS-Excel, Machine Learning, Python",Kongu Engineering College,Bachelor of Engineering (B.E),E &amp;i,2015
96,Bangalore,2,0,2,"MS-Excel, Machine Learning, Python, SQL, Natural Language Processing (NLP)",Bapuji Institute of Engineering and Technology,Bachelor of Engineering (B.E),Mechanical Engineering,2014
97,Bangalore,2,1,0,"C Programming, English Proficiency (Spoken), English Proficiency (Written), Python, SQL, Tableau, R Programming, Statistical Modeling","Bangalore Institute of Technology, Bangalore",Bachelor of Engineering (B.E),Electronics and Communication,2018
98,Mumbai,2,2,2,"Image Processing, OpenCV, Artifical Intelligence, C Programming, Data Analytics, Database Management System (DBMS), Deep Learning, Financial Modeling, MS SQL Server, MS-Excel, MS-PowerPoint, Machine Learning, Mathematics, Microsoft Visual Studio, Python, R Programming, SPSS, SQL",Narsee Monjee Institute of Management studies,Bachelor of Science (B.Sc),Applied Statistics And Analytics,2020
99,Bangalore,2,0,2,"C Programming, Deep Learning, Java, Machine Learning, Natural Language Processing (NLP), Python, SQL",Donbosco Institite Of Technology,Bachelor of Engineering (B.E),Computer Science & Engineering,2018
100,Ahmedabad,2,0,2,"Data Analytics, MS SQL Server, MS-Excel, Machine Learning, Python, Power BI",International Institute Of Information Technology Bangalore,NaN,Data Science,2020
102,Bangalore,2,0,2,"SQL, Data Analytics, Data Science, MS-Excel, Machine Learning, Python, Statistical Modeling",Great Lakes Institute of Management,Post Graduate Programme (PGP),Data Science And Engineering,2020
103,Thrissur,1,0,0,"Adobe Illustrator, Adobe Photoshop, CSS, HTML, JavaScript, SQL, Data Analytics, Python","MACFAST, Thriuvalla",Master of Computer Applications (MCA),Computer Science,2016
104,Hyderabad,2,0,2,"MySQL, Data Analytics, MS-Excel, Machine Learning, Python, Tableau",Kallam Haranadhareddy Institute Of Technology,Bachelor of Technology (B.Tech),Electronics and Communication,2018
105,Bangalore,2,0,0,"Bootstrap, C Programming, C++ Programming, CSS, HTML, Java, JavaScript, PHP, Python, SQL, jQuery, Android, Data Science, iOS",SASTRA DEEMED UNIVERSITY,Bachelor of Technology (B.Tech),Computer Science & Engineering,2018
106,Hyderabad,2,2,2,"English Proficiency (Spoken), Machine Learning, Python, R Programming, Data Analytics, MS-Excel, SQL",Vmritms,Bachelor of Technology (B.Tech),Electrical and Electronics Engineering,2013
107,Bangalore,1,1,1,"Machine Learning, Microsoft Azure, Python, R Programming",Institute Of Technical Education & Research,Master of Technology (M.Tech),Computer Science,2017
109,Banglore,3,2,2,"Data Analytics, MySQL, Python, Hadoop, Java, Machine Learning, R Programming","National Institute Of Electronics & Information Technology, Calicut",NaN,Advanced Diploma In BigData Analytics,2020
112,Bangalore,1,2,0,"Data Analytics, MS-Excel, Power BI, R Programming, SAP, Data Science, Python, SQL",Myra School Of Business,Post Graduate Diploma in Management (P.G.D.M.),Data Analytics,2019
113,Delhi,0,3,0,"R Programming, SAS","Amity University, Noida",Master of Science (M.Sc),Applied Mathematics,2017
114,Bangalore,2,0,2,"Data Structures, Machine Learning, Python, SQL",QUTUBSHAHI PG COLLEGE FOR MCA,Master of Computer Applications (MCA),Computer Science,2009
115,Vijayawada,2,0,1,"Data Analytics, Python, Artifical Intelligence, Machine Learning",VR Siddhartha Engineering College,Master of Computer Applications (MCA),Computer Application,2018
116,Lucknow,2,0,0,"Algorithms, C++ Programming, Data Structures, Database Management System (DBMS), Python, Java",Baba Saheb Bhim Rao Ambedkar University,Master of Computer Applications (MCA),NaN,2020
117,Bangalore,2,2,2,"CSS, HTML, JavaScript, jQuery, .NET, ASP.NET, Adobe Photoshop Lightroom CC, C#.NET, Machine Learning, Python, R Programming, SQL",BEC,Bachelor of Technology (B.Tech),Electronics and Telecommunication Engineering (ETE),2013
118,Bangalore,3,0,3,"Data Analytics, English Proficiency (Spoken), MS-Excel, Machine Learning, Python",Great Lakes Institute of Management,PG Diploma in Data Science,Data Analytics,2020
119,Bangalore,2,2,3,"Data Analytics, MS-Excel, MS-Office, Machine Learning, Artifical Intelligence, Python, R Programming, BIG DATA ANALYTICS",Insofe,Post Graduate Programme (PGP),Data Science,2020
120,Bangalore,1,0,0,"CSS, HTML, Java, JavaScript, Python",CMR Institute Of Technology,Master of Computer Applications (MCA),Computer Applications,2020
121,Bangalore,2,0,2,"MS-Excel, MS-Word, Data Analytics, Machine Learning, Python, SQL",G H Raisoni College Of Engineering & Management,Master of Engineering (M.E),Mechanical Engineering,2015
122,Bangalore,3,0,3,"Algorithms, C Programming, C++ Programming, Data Analytics, Data Science, Data Structures, MS-Excel, MS-Word, Machine Learning, Python, Statistical Modeling, Database Management System (DBMS), SQL",Vadodara Institute Of Engineering,Bachelor of Engineering (B.E),Computer Science & Engineering,2018
123,Bangalore,2,0,2,"MS-Excel, Data Analytics, Machine Learning, MySQL, Python, Statistical Modeling, Tableau",Great Lakes Institute of Management,Post Graduate Programme (PGP),Business Analytics And Business Intelligence,2020
124,Kottayam,0,0,0,Statistical Modeling,ExcelR Banglore,NaN,Data Science,2020
125,Pune,1,0,1,"Machine Learning, Python",Tatyasaheb Kore Institute Of Engineering & Technology,Bachelor of Technology (B.Tech),Mechanical,2018
126,Hyderabad,2,2,2,"Machine Learning, Natural Language Processing (NLP), OpenCV, Python, R Programming, Artifical Intelligence, Deep Learning","National Institute Of Electronics & Information Technology, Calicut",NaN,Artificial Intelligence,2020

In [13]:
# Lets check the null values after dropping some records.
(ibdf.isnull().sum()*100)/ibdf.shape[0]

Current City                  0.000000
Python (out of 3)             0.000000
R Programming (out of 3)      0.000000
Data Science (out of 3)       0.000000
Other skills                  1.636661
Institute                     0.000000
Degree                        5.891980
Stream                        5.073650
Current Year Of Graduation    0.000000
dtype: float64

- As you can see most of the missing values have been treated. Now we are leaft with less than 6% of missing values.
Lets treat the remaining missing records.

- #### Lets find the unique value count of records with datatype 'object'.

In [14]:
# Checking the value counts of the features having the object data type. 
objectdtypes=list(ibdf.select_dtypes(include='object').columns)
for i in objectdtypes:
    print('Value counts of {0} '.format(i))
    print(ibdf[i].value_counts())
    print('================================')

Value counts of Current City
Bangalore            334
Hyderabad             52
Pune                  29
Chennai               23
Banglore              17
Delhi                 17
Mumbai                14
Kolkata                7
Thrissur               7
Noida                  6
Kozhikode              5
Visakhapatnam          5
Indore                 4
Nellore                4
Jaipur                 4
Nagpur                 4
Varanasi               4
Bhubaneswar            4
Jalandhar              4
Ahmedabad              3
Kharagpur              3
Lucknow                3
Kochi                  3
Chandigarh             2
Ranchi                 2
Agartala               2
Greater Noida          2
Dharwad                2
Coimbatore             2
Dehradun               2
Vellore                2
Tirupati               1
Ajmer                  1
Bokaro Steel City      1
Wardha                 1
Salem                  1
Raebareli              1
New Delhi              1
Ernakulam              1
Akola                  1
Dhanbad                1
Nashik                 1
Gandhinagar            1
Vijayawada             1
Jamshedpur             1
Idupulapaya            1
Gwalior                1
Kolhapur               1
Patna                  1
Malvern                1
Roorkee                1
Thane                  1
Meerut                 1
Kottayam               1
Barhampur              1
Pathanamthitta         1
Bhopal                 1
Gangtok                1
Bathinda               1
Ghaziabad              1
Durgapur               1
Guna                   1
Rourkela               1
Vadodara               1
Bhiwadi                1
Gulbarga               1
Agra                   1
Mangaluru              1
Guntur                 1
Karjat                 1
Name: Current City, dtype: int64
================================
Value counts of Other skills
Data Analytics, Machine Learning, Python                                                                                                                                                                                                                                                                                                                                                                                                                              5
Machine Learning, Python                                                                                                                                                                                                                                                                                                                                                                                                                                              5
Data Analytics, English Proficiency (Spoken), MS-Excel, Machine Learning, Python                                                                                                                                                                                                                                                                                                                                                                                      3
Data Analytics                                                                                                                                                                                                                                                                                                                                                                                                                                                        3
Machine Learning, Python, R Programming, Statistical Modeling, Apache, Hadoop                                                                                                                                                                                                                                                                                                                                                                                         2
CSS, HTML, JavaScript, jQuery, .NET, ASP.NET, Adobe Photoshop Lightroom CC, C#.NET, Machine Learning, Python, R Programming, SQL                                                                                                                                                                                                                                                                                                                                      2
SQL, Data Analytics, Data Science, MS-Excel, Machine Learning, Python, Statistical Modeling                                                                                                                                                                                                                                                                                                                                                                           2
Algorithms, C Programming, Data Structures, Database Management System (DBMS), Java, Linux, Python                                                                                                                                                                                                                                                                                                                                                                    2
English Proficiency (Spoken), MS-Excel, Data Analytics, Machine Learning, Python                                                                                                                                                                                                                                                                                                                                                                                      2
C Programming, Python, R Programming                                                                                                                                                                                                                                                                                                                                                                                                                                  2
BIG DATA ANALYTICS, Data Analytics, Database Management System (DBMS), Machine Learning, MySQL, Natural Language Processing (NLP), Python                                                                                                                                                                                                                                                                                                                             2
C Programming, C++ Programming, Data Analytics, MS-Excel, Machine Learning, Python, R Programming, SQL                                                                                                                                                                                                                                                                                                                                                                2
SQL, Algorithms, Data Analytics, Data Structures, MS-Excel, Machine Learning, Mathematics, Python                                                                                                                                                                                                                                                                                                                                                                     2
Data Analytics, MS-Excel, Machine Learning, Python, Deep Learning, OpenCV                                                                                                                                                                                                                                                                                                                                                                                             2
AutoCAD, MS-Excel, Deep Learning, Machine Learning, MySQL, Natural Language Processing (NLP), Python, R Programming, SolidWorks, Statistical Modeling                                                                                                                                                                                                                                                                                                                 2
Artifical Intelligence, Computer Vision, Deep Learning, Machine Learning, Natural Language Processing (NLP), Python, R Programming, SQL, Statistical Modeling, Tableau                                                                                                                                                                                                                                                                                                2
MS-PowerPoint, Accounting, MS-Excel, CorelDRAW, MySQL, Python, R Programming                                                                                                                                                                                                                                                                                                                                                                                          2
Machine Learning, Natural Language Processing (NLP), OpenCV, Python, R Programming, Artifical Intelligence, Deep Learning                                                                                                                                                                                                                                                                                                                                             2
Computer Vision, Deep Learning, Machine Learning, MySQL, Natural Language Processing (NLP), Python, Statistical Modeling                                                                                                                                                                                                                                                                                                                                              2
Machine Learning, Microsoft Azure, Python, R Programming                                                                                                                                                                                                                                                                                                                                                                                                              2
Data Analytics, Data Science, MS-Excel, Machine Learning, Python                                                                                                                                                                                                                                                                                                                                                                                                      2
Data Analytics, MS-Office, Python, Algorithms, Data Science, Data Structures, Database Management System (DBMS), GitHub, MS-Excel, Machine Learning, Mathematics, OpenCV, SQL, Statistical Modeling, Natural Language Processing (NLP)                                                                                                                                                                                                                                2
Data Analytics, Database Management System (DBMS), Python, Machine Learning                                                                                                                                                                                                                                                                                                                                                                                           2
C Programming, Data Analytics, Machine Learning, Python, Deep Learning, Java, Natural Language Processing (NLP), SQL                                                                                                                                                                                                                                                                                                                                                  2
C Programming, Computer Vision, Database Management System (DBMS), Digital Marketing, Mathematics, Data Analytics, Data Structures, Java, Python, XML, AngularJS, Machine Learning, OpenCV                                                                                                                                                                                                                                                                            2
Python, SQL                                                                                                                                                                                                                                                                                                                                                                                                                                                           2
Artifical Intelligence, Machine Learning, Python, SQL                                                                                                                                                                                                                                                                                                                                                                                                                 2
MS-Excel, Python, Machine Learning                                                                                                                                                                                                                                                                                                                                                                                                                                    2
Algorithms, C++ Programming, Data Analytics, Data Structures, Machine Learning, Mathematics, Python                                                                                                                                                                                                                                                                                                                                                                   2
CSS, HTML, Adobe Dreamweaver, BIG DATA ANALYTICS, C Programming, Computer Networking, Computer Networks, Data Analytics, Deep Learning, Image Processing, Machine Learning, MongoDB, NoSQL, SQL, C++ Programming, Data Structures, Ethical Hacking, R Programming                                                                                                                                                                                                     2
MS-Excel, SQL, Machine Learning, Python, R Programming                                                                                                                                                                                                                                                                                                                                                                                                                2
MS-Excel, MS-Office, Python, C Programming, C++ Programming, CSS, Data Analytics, Database Management System (DBMS), Email Marketing, HTML, Java, MS-PowerPoint, MS-Word, Machine Learning, MySQL, R Programming, SQL, Artifical Intelligence, Deep Learning, Neural Networks, WordPress                                                                                                                                                                              2
MS-Excel, Python, R Programming, SAS                                                                                                                                                                                                                                                                                                                                                                                                                                  2
C Programming, Python, C++ Programming, Java, R Programming, Search Engine Optimization (SEO)                                                                                                                                                                                                                                                                                                                                                                         2
MS-Excel, Data Analytics, Machine Learning, MySQL, Python, Statistical Modeling                                                                                                                                                                                                                                                                                                                                                                                       2
MS-Excel, PostgreSQL, Python, BIG DATA ANALYTICS, GitHub, Natural Language Processing (NLP), OpenCV, Deep Learning, MongoDB                                                                                                                                                                                                                                                                                                                                           2
Data Analytics, Machine Learning, Python, Artifical Intelligence, Deep Learning, Natural Language Processing (NLP), Computer Vision, Image Processing                                                                                                                                                                                                                                                                                                                 2
Machine Learning, Arduino, C Programming, CSS, Data Analytics, Data Structures, Deep Learning, HTML, Natural Language Processing (NLP), MATLAB, Python                                                                                                                                                                                                                                                                                                                2
Machine Learning, AutoCAD, Autodesk Inventor, Data Analytics, Database Management System (DBMS), MySQL, Python, Statistical Modeling, MATLAB, Natural Language Processing (NLP)                                                                                                                                                                                                                                                                                       2

In [15]:
# Checking the value counts of the features having the integer data type. These features are stored in a variable named dummy_vars.
# Features in Dummy_vars will be used to create dummy features
dummy_vars=[]
for i in objectdtypes:
    if len(ibdf[i].value_counts())>2:
        print('Value counts of {0} : '.format(i),len(ibdf[i].value_counts()))
        print('================================')
        dummy_vars.append(i)

Value counts of Current City :  70
================================
Value counts of Other skills :  513
================================
Value counts of Institute :  439
================================
Value counts of Degree :  42
================================
Value counts of Stream :  120
================================

In [16]:
ibdf['Current City'].replace(to_replace='Banglore',value='Bangalore',inplace=True)

In [17]:
# Lets check the null values after dropping some records.
(ibdf.isnull().sum()*100)/ibdf.shape[0]

Current City                  0.000000
Python (out of 3)             0.000000
R Programming (out of 3)      0.000000
Data Science (out of 3)       0.000000
Other skills                  1.636661
Institute                     0.000000
Degree                        5.891980
Stream                        5.073650
Current Year Of Graduation    0.000000
dtype: float64

In [18]:
ibdf.dropna(inplace=True)

In [19]:
(ibdf.isnull().sum()*100)/ibdf.shape[0]

Current City                  0.0
Python (out of 3)             0.0
R Programming (out of 3)      0.0
Data Science (out of 3)       0.0
Other skills                  0.0
Institute                     0.0
Degree                        0.0
Stream                        0.0
Current Year Of Graduation    0.0
dtype: float64

In [20]:
ibdf['Degree'].value_counts()

Bachelor of Technology (B.Tech)                              158
Bachelor of Engineering (B.E)                                133
Master of Technology (M.Tech)                                 37
Master of Science (M.Sc)                                      32
B.Tech (Hons.)                                                27
Master of Computer Applications (MCA)                         25
PG Diploma in Data Science                                    16
Post Graduate Programme (PGP)                                 16
Bachelor of Science (B.Sc)                                    16
MBA                                                           13
Integrated B.Tech                                              4
Integrated M.Sc.                                               4
Bachelor of Computer Applications (BCA)                        4
Bachelor of Commerce (B.Com)                                   4
Post Graduate Diploma                                          4
Master of Science (M.Sc) (Hons.)                               4
Integrated B.Tech & M.Tech                                     3
Integrated M.Tech                                              3
Master of Science (M.S.)                                       3
Post Graduate Diploma in Management (P.G.D.M.)                 3
Master of Arts (M.A.)                                          3
Master of Business Administration_(MBA)                        3
Master Of Analytics                                            2
Bachelor of Computer Science (B.C.S.)                          2
Master of Statistics (M.Stat)                                  2
Bachelor of Science (B.Sc) (Hons.)                             2
Integrated B.Tech & MBA                                        1
Integrated B.Sc. & M.Sc.                                       1
Post Graduate Diploma in Big Data Analytics (PG-DBDA)          1
Master of Engineering (M.E)                                    1
Bachelor of Engineering (B.E) (Hons.)                          1
Bachelor of Commerce (B.Com) (Hons.)                           1
Integrated B.S. & M.S.                                         1
Post Graduate Diploma in Business Management (P.G.D.B.M.)      1
Bachelor of Mathematics (B.Math) (Hons.)                       1
Executive MBA                                                  1
Bachelor of Business Management (B.B.M.)                       1
Post Graduate Program in Business Analytics                    1
Name: Degree, dtype: int64

In [21]:
ibdf['Stream'].replace(['computer science','Computer  Science','cs','Computer Science  Engineering','Computer Science & Engineering (CSE)','Computer Science & Engineering','Computer Science &amp;engineering','Computer Science AndEngineering'],"Compuer Science",inplace=True)
ibdf['Degree'].replace(['B.Tech (Hons.)', 'Bachelor of Technology (B.Tech)', 'Bachelor of Engineering (B.E)', 'Integrated B.Tech', 'Bachelor of Engineering (B.E) (Hons.)', 'Bachelor of Engineering (B.E) (Hons.)', 'Integrated B.Tech & M.Tech'], 'BE/BTech',inplace=True)
ibdf['Degree'].replace(['Integrated B.S. & M.S.','Master of Science (M.S.)', 'Master of Science (M.Sc)','Master of Technology (M.Tech)', 'Master of Science (M.Sc) ', 'Master of Engineering (M.E)', 'Integrated B.Sc. & M.Sc.', 'Integrated B.Tech', 'Master of Science (M.Sc) (Hons.)', 'Integrated M.Tech', 'Integrated B.Tech & M.Tech', 'Integrated M.Sc.'],'Msc/MTech',inplace=True)

In [22]:
ibdf['Degree'].value_counts()

BE/BTech                                                     326
Msc/MTech                                                     86
Master of Computer Applications (MCA)                         25
Post Graduate Programme (PGP)                                 16
PG Diploma in Data Science                                    16
Bachelor of Science (B.Sc)                                    16
MBA                                                           13
Bachelor of Commerce (B.Com)                                   4
Post Graduate Diploma                                          4
Bachelor of Computer Applications (BCA)                        4
Post Graduate Diploma in Management (P.G.D.M.)                 3
Master of Arts (M.A.)                                          3
Master of Business Administration_(MBA)                        3
Master of Statistics (M.Stat)                                  2
Bachelor of Computer Science (B.C.S.)                          2
Bachelor of Science (B.Sc) (Hons.)                             2
Master Of Analytics                                            2
Post Graduate Diploma in Business Management (P.G.D.B.M.)      1
Bachelor of Mathematics (B.Math) (Hons.)                       1
Executive MBA                                                  1
Bachelor of Commerce (B.Com) (Hons.)                           1
Integrated B.Tech & MBA                                        1
Bachelor of Business Management (B.B.M.)                       1
Post Graduate Program in Business Analytics                    1
Post Graduate Diploma in Big Data Analytics (PG-DBDA)          1
Name: Degree, dtype: int64

In [23]:
# # Visualisaing the data
# plt.figure(figsize=(7,6))

# #plotting heat map to find the correlations between different features
# sns.heatmap(ibdf[top_corr_features].corr(),annot=True,cmap="RdYlGn")
# plt.show()

In [24]:
# plt.figure(figsize=(7,4))
# sns.pairplot(data=ibdf.select_dtypes(exclude='object'))
# plt.show()

In [25]:
credits=['Machine Learning','Deep Learning','NLP','Statistical Data Analysis','AWS','SQL/NoSQL','Excel']
other_skills=list(ibdf['Other skills'].str.split(','))

# ibdf['Other skills'] = ibdf['Other skills'].str.replace(" Statistical Modeling","Statistical Data Analysis") 
ibdf['Other skills'] = ibdf['Other skills'].str.replace(" Amazon Web Services (AWS)","AWS")

In [26]:
ibdf['Other skills'].head(100)

0                                                                                                                                              Machine Learning, Arduino, C Programming, CSS, Data Analytics, Data Structures, Deep Learning, HTML, Natural Language Processing (NLP), MATLAB, Python
2                                                                                                                                                                                                                                          C++ Programming, Data Structures, Image Processing, Python
3                                                                                                                          Algorithms, C++ Programming, Data Structures, Natural Language Processing (NLP), CSS, Computer Vision, Deep Learning, HTML, Java, Machine Learning, MySQL, Python, Android
4                                                                                                                                                                                                                                                                      MS-Word, Python, SQL, MS-Excel
5                                                                                                                                                                                         C Programming, C++ Programming, CSS, GitHub, HTML, MS-Office, Python, R Programming, SQL, JavaScript, STATA
6                                                                                                                                                                                                                                                    C++ Programming, Deep Learning, Machine Learning
7                                                                                                                                                                                                                                       Natural Language Processing (NLP), Python, R Programming, SQL
8                                                                                                                                                                                                           Computer Vision, Image Processing, MySQL, OpenCV, Python, Deep Learning, Machine Learning
9                                                                                                                                                                                                                                                                   CSS, HTML, JavaScript, PostgreSQL
10                                                                                                                                                                                                                   English Proficiency (Spoken), MS-Excel, Data Analytics, Machine Learning, Python
11                                                                                                                                                                                                              MS-Excel, MS-Office, SPSS, Data Science, Machine Learning, R Programming, SQL, Python
12                                                                                                                                                                                                            C Programming, Eclipse (IDE), Java, Database Management System (DBMS), HTML, Linux, SQL
13                                                                                                                                                                                                                                                              AutoCAD, MS-Office, Catia, SolidWorks
14                                                                                                                                                                                                                                     Machine Learning, Python, MySQL, Statistical Modeling, Tableau
15                                                                                                                                                                                                                                                                  AutoCAD, Embedded Systems, MATLAB
16                                                                                                Bootstrap, C Programming, Flask, HTML, LARAVEL, MySQL, Node.js, PHP, PostgreSQL, Python, SQL, Stripe Payment API, Video Editing, Data Analytics, GitHub, Heroku, Image Processing, Machine Learning
19                                                                                                                                                                                                                                              HTML, MS-Excel, SQL, Android, JavaScript, PHP, Python
20                                                                                                                                                                                                                          Data Analytics, Embedded Systems, Machine Learning, Python, R Programming
21                                                                                                                                                                                                 Algorithms, C Programming, Data Structures, Database Management System (DBMS), Java, Linux, Python
22                                                                                                            Python, SQL, Amazon Web Services (AWS), Apache Cassandra, Apache Kafka, BIG DATA ANALYTICS, Cloud Computing, Database Management System (DBMS), Hadoop, Linux, MongoDB, Shell Scripting
23                                                                                                                                                                                                                                                       Python, Machine Learning, SQL, R Programming
24                                                                                           Python, Data Analytics, Data Science, MS-PowerPoint, MS-Word, Machine Learning, Mathematics, Video Editing, C Programming, Data Structures, Database Management System (DBMS), MS SQL Server, MySQL, SQL
26                                                                                                                                                                                                  Computer Networking, Data Analytics, Data Science, Linux, MS-Excel, Machine Learning, Python, SQL
27                                                                                                                                                                 C Programming, C++ Programming, Java, MS-Excel, MS-Office, MS-PowerPoint, MS-Word, WordPress, HTML, Python, SQL, Visual Basic (VB)
28                                                                                                                                                                                                Algorithms, C++ Programming, Data Analytics, Data Structures, Machine Learning, Mathematics, Python
30                                                                                                                                                                                                                                                Data Analytics, Java, Machine Learning, Python, SQL
31                                                                                                                                                                                                                         Machine Learning, Python, R Programming, Natural Language Processing (NLP)
32                                                                                                                                                                                                                                     English Proficiency (Spoken), MS-Excel, Data Analytics, Python
35                                                                                                                                                                                                   ASP.NET, C#, HTML, JavaScript, Machine Learning, SQL, Data Science, Python, Statistical Modeling
36                                                                                                                                                                                                                      PLC SCADA, Embedded Systems, MATLAB, MS-Office, VHDL, C Programming, MS-Excel
37                                                                                                                                                                                                       Database Management System (DBMS), MS-Office, Data Analytics, Python, Java, Machine Learning
39                                                                                                                                                                                                                      Machine Learning, Python, R Programming, Statistical Modeling, Apache, Hadoop
40                                                                                                                                                               C Programming, C++ Programming, Data Analytics, Java, MS-Excel, Machine Learning, MySQL, Python, R Programming, Statistical Modeling
41                                                                                                                                                                                                                                                            C Programming, Python, Machine Learning
42                                                                                                                                                                                   Data Analytics, Data Science, Deep Learning, Machine Learning, Python, R Programming, SQLite, Apache, MySQL, SQL
43                                                                                                                                                                                                                             Google Analytics, MS-Excel, MS-PowerPoint, MS-Word, SQL, R Programming
44                                                                         English Proficiency (Written), C Programming, C++ Programming, English Proficiency (Spoken), HTML, MS-Excel, MS-Office, MS-PowerPoint, MS-Word, Machine Learning, Python, SQLite, Adobe Photoshop, Algorithms, JSON, MySQL
45                                                                                                                                                                                                                                                               C Programming, Python, R Programming
46                                                                                                                                                                                 CSS, Django, HTML, Machine Learning, MySQL, Python, Data Analytics, Deep Learning, MATLAB, Neural Networks, OpenCV
47                                                                                                                                                                                                                                                Machine Learning, C Programming, Data Science, Java
48                                                                                                                                                                                                                                                                                     Data Analytics
49                                                                                                         C Programming, Computer Vision, Database Management System (DBMS), Digital Marketing, Mathematics, Data Analytics, Data Structures, Java, Python, XML, AngularJS, Machine Learning, OpenCV
50                                                                                                                                                                                                                                         Machine Learning, MySQL, Python, SAS, Statistical Modeling
51                                                                                                                                                                                                        Data Analytics, Machine Learning, English Proficiency (Spoken), Java, MS-Excel, Python, SQL
52                                                                                                                                                                                                                     Python, AutoCAD, C Programming, C++ Programming, Java, Machine Learning, MySQL
53                                                                                                                                      Data Analytics, Machine Learning, Python, Statistical Modeling, Computer Vision, Image Processing, MS-Excel, Natural Language Processing (NLP), Deep Learning
54                                                                                                                                                          BIG DATA ANALYTICS, Data Analytics, Database Management System (DBMS), Machine Learning, MySQL, Natural Language Processing (NLP), Python
55                                                                                                                                                                                                                           C Programming, C++ Programming, CSS, Data Structures, HTML, Java, Python
57                                                                                                                                                                                                                                                    MS-Excel, Python, SAP, R Programming, SPSS, SQL
59                                                                                                                                                                                                                                   English Proficiency (Spoken), MS-Excel, Machine Learning, Python
60                                                                                                                                                                                                    English Proficiency (Spoken), English Proficiency (Written), MS-Excel, Machine Learning, Python
61                                                                                                                                                                                                                                                                                      R Programming
62                                                                                                                                                                                                                                                    MS-Excel, MySQL, R Programming, Python, Tableau
63                                                                                                                                                                                                                                                           Machine Learning, Python, Data Analytics
64                                                                                                                                                                                                                                       C Programming, C++ Programming, CSS, HTML, Java, Python, SQL
65                                                                                                                                                                                                                                                                                       Data Science
66                                                                                                                                                                                                      Data Analytics, Deep Learning, Eclipse (IDE), HTML, MS-Excel, Machine Learning, MySQL, Python
67                                                                                                                                                                                                                                                   Data Analytics, Python, SPSS, SQL, R Programming
69                                                                                                                                                                                       C Programming, C++ Programming, GNU Octave, Java, MS-Excel, MS-PowerPoint, MS-Word, Python, Machine Learning
70                                                                                                                                                                                                                                                                    Machine Learning, MySQL, Python
71                                                                                                                                                                                                                         MS-Excel, MySQL, Python, R Programming, SAS, Statistical Modeling, Tableau
72     C Programming, C++ Programming, CSS, Data Structures, Database Management System (DBMS), Deep Learning, Flask, HTML, JavaScript, Linux, MATLAB, Machine Learning, Node.js, OpenCV, PHP, Python, jQuery, BIG DATA ANALYTICS, Data Science, Django, Image Processing, JSON, Neural Networks, SQL
73                                                                                                                                                                                             Hibernate (Java), MySQL, C Programming, C++ Programming, CSS, HTML, Java, Spring MVC, Machine Learning
74                                                                                                                                                                                                         Adobe Photoshop, CSS, HTML, Java, JavaScript, Machine Learning, PHP, Python, R Programming
75                                                                                                                                                                                             C Programming, C++ Programming, Data Analytics, MS-Excel, Machine Learning, Python, R Programming, SQL
76                                                                                                                                                                    Data Science, Deep Learning, Machine Learning, Natural Language Processing (NLP), Python, Artifical Intelligence, R Programming
77                                                                                                                                                                                                                                ASP.NET, C#, HTML, Python, SQL, Visual Basic (VB), Machine Learning
78                                                                                                                                                                                                                                                                                   Python, SAS, SQL